## Sorting Contours

We can sort contours in many ways.

In [1]:
import cv2
import numpy as np

# Load our image
image = cv2.imread('bunchofshapes.jpg')
cv2.imshow('0 - Original Image', image)
cv2.waitKey(0)

# Create a black image with same dimensions as our loaded image
blank_image = np.zeros((image.shape[0], image.shape[1], 3))

# Create a copy of our original image
orginal_image = image.copy()

# Grayscale our image
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# Find Canny edges
edged = cv2.Canny(gray, 50, 200)
cv2.imshow('1 - Canny Edges', edged)
cv2.waitKey(0)

# Find contours and print how many were found
contours, hierarchy = cv2.findContours(edged,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_NONE)
print ("Number of contours found = ", len(contours))

#Draw all contours
cv2.drawContours(blank_image, contours, -1, (0,255,0), 3)
cv2.imshow('2 - All Contours over blank image', blank_image)
cv2.waitKey(0)

# Draw all contours over blank image
cv2.drawContours(orginal_image, contours, -1, (0,255,0), 3)
cv2.imshow('3 - All Contours', orginal_image)
cv2.waitKey(0)

cv2.destroyAllWindows()

Number of contours found =  4


### Let's now sort by area

In [2]:
import cv2
import numpy as np

# Function we'll use to display contour area

def get_contour_areas(contours):
    # returns the areas of all contours as list
    all_areas = []
    for cnt in contours:
        area = cv2.contourArea(cnt)
        all_areas.append(area)
    return all_areas

# Load our image

image = cv2.imread('bunchofshapes.jpg')
orginal_image = image.copy()
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# Find Canny edges
edged = cv2.Canny(gray, 50, 200)
cv2.imshow('1 - Canny Edges', edged)
cv2.waitKey(0)

# Find contours and print how many were found
contours, hierarchy = cv2.findContours(edged,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_NONE)
print ("Number of contours found = ", len(contours))

# Let's print the areas of the contours before sorting
print ("Contor Areas before sorting", )
print (get_contour_areas(contours))

# Sort contours large to small
sorted_contours = sorted(contours, 
                         key=cv2.contourArea, reverse=True)
#sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)[:3]

print("Contor Areas after sorting") 
print (get_contour_areas(sorted_contours))

# Iterate over our contours and draw one at a time
for c in sorted_contours:
    cv2.drawContours(orginal_image, [c], -1, (255,0,0), 3)
    cv2.waitKey(0)
    cv2.imshow('Contours by area', orginal_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contours found =  4
Contor Areas before sorting
[20587.5, 22901.5, 66579.5, 90222.0]
Contor Areas after sorting
[90222.0, 66579.5, 22901.5, 20587.5]


In [5]:
a = np.random.randint(0,100,20)
b = np.random.randint(0,100,20)
my_list = list(zip(a,b))
sorted(my_list,key=lambda x:x[1])

[(68, 1),
 (64, 5),
 (2, 6),
 (11, 25),
 (67, 30),
 (29, 31),
 (39, 36),
 (13, 45),
 (42, 53),
 (57, 56),
 (23, 61),
 (95, 69),
 (12, 69),
 (44, 71),
 (11, 72),
 (29, 72),
 (13, 75),
 (34, 91),
 (21, 91),
 (59, 93)]

In [6]:
def sort_1id(x):
    return x[1]
a = np.random.randint(0,100,20)
b = np.random.randint(0,100,20)
my_list = list(zip(a,b))
sorted(my_list,key=sort_1id)

[(41, 3),
 (26, 9),
 (94, 11),
 (86, 15),
 (67, 27),
 (80, 29),
 (10, 37),
 (21, 39),
 (57, 44),
 (7, 45),
 (89, 46),
 (74, 47),
 (11, 59),
 (71, 65),
 (49, 71),
 (33, 79),
 (11, 82),
 (99, 92),
 (75, 95),
 (72, 99)]

In [7]:
my_list

[(49, 71),
 (72, 99),
 (11, 59),
 (57, 44),
 (21, 39),
 (7, 45),
 (74, 47),
 (75, 95),
 (41, 3),
 (10, 37),
 (80, 29),
 (33, 79),
 (86, 15),
 (99, 92),
 (11, 82),
 (94, 11),
 (26, 9),
 (71, 65),
 (67, 27),
 (89, 46)]

In [8]:
import cv2
import numpy as np


def key_area(contour):
    area = cv2.contourArea(contour)
    return area


image = cv2.imread('bunchofshapes.jpg')
orginal_image = image
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

edged = cv2.Canny(gray, 50, 200)

contours, hierarchy = cv2.findContours(edged.copy(),
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_NONE)
sorted_contours = sorted(contours, 
                         key=key_area, reverse=True)
for c in sorted_contours:
    cv2.drawContours(orginal_image, [c], -1, (255,0,0), 3)
    cv2.waitKey(0)
    cv2.imshow('Contours by area', orginal_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
contours

[array([[[817, 370]],
 
        [[816, 371]],
 
        [[815, 371]],
 
        ...,
 
        [[820, 370]],
 
        [[819, 370]],
 
        [[818, 370]]], dtype=int32),
 array([[[596, 345]],
 
        [[596, 346]],
 
        [[595, 347]],
 
        ...,
 
        [[599, 346]],
 
        [[598, 345]],
 
        [[597, 345]]], dtype=int32),
 array([[[1262,  258]],
 
        [[1261,  259]],
 
        [[1260,  259]],
 
        ...,
 
        [[1265,  258]],
 
        [[1264,  258]],
 
        [[1263,  258]]], dtype=int32),
 array([[[135, 245]],
 
        [[135, 246]],
 
        [[134, 247]],
 
        ...,
 
        [[138, 245]],
 
        [[137, 245]],
 
        [[136, 245]]], dtype=int32)]

In [10]:
cv2.moments(contours[0])

{'m00': 20587.5,
 'm10': 18250924.833333332,
 'm01': 9099782.333333332,
 'm20': 16214606883.25,
 'm11': 8067011518.125,
 'm02': 4057711167.4166665,
 'm30': 14436508422455.451,
 'm21': 7166954589089.566,
 'm12': 3597188928206.5664,
 'm03': 1824964836980.2002,
 'mu20': 35067975.07837677,
 'mu11': 7590.238600730896,
 'mu02': 35559934.190416336,
 'mu30': -11432.6015625,
 'mu21': 353952.1429042816,
 'mu12': 359855.0387878418,
 'mu03': -6583.537353515625,
 'nu20': 0.08273770399700484,
 'nu11': 1.7908046107890125e-05,
 'nu02': 0.0838984088081491,
 'nu30': -1.8799055832427544e-07,
 'nu21': 5.820167929485615e-06,
 'nu12': 5.9172314619470645e-06,
 'nu03': -1.0825557560719243e-07}

In [11]:
import cv2
import numpy as np

# Functions we'll use for sorting by position

def x_cord_contour(contour):
    #Returns the X cordinate for the contour centroid
    if cv2.contourArea(contour) > 10:
        M = cv2.moments(contour)
        return (int(M['m10']/M['m00']))
    else:
        pass

    
def label_contour_center(image, c):
    # Places a red circle on the centers of contours
    M = cv2.moments(c)
    cx = int(M['m10'] / M['m00'])
    cy = int(M['m01'] / M['m00'])
 
    # Draw the countour number on the image
    cv2.circle(image,(cx,cy), 10, (0,0,255), -1)
    return image


# Load our image
image = cv2.imread('bunchofshapes.jpg')
orginal_image = image.copy()


# Computer Center of Mass or centroids and draw them on our image
for (i, c) in enumerate(contours):
    orig = label_contour_center(image, c)
 
    cv2.imshow("4 - Contour Centers ", image)
    cv2.waitKey(0)

# Sort by left to right using our x_cord_contour function
contours_left_to_right = sorted(contours, 
                                key = x_cord_contour, 
                                reverse = False)


# Labeling Contours left to right
for (i,c)  in enumerate(contours_left_to_right):
    cv2.drawContours(orginal_image, [c], -1, (0,0,255), 3)  
    M = cv2.moments(c)
    cx = int(M['m10'] / M['m00'])
    cy = int(M['m01'] / M['m00'])
    cv2.putText(orginal_image, str(i+1), (cx, cy), 
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('6 - Left to Right Contour', orginal_image)
    cv2.waitKey(0)
    (x, y, w, h) = cv2.boundingRect(c)  
        
    # Let's now crop each contour and save these images
    cropped_contour = orginal_image[y:y + h, x:x + w]
    image_name = "output_shape_number_" + str(i+1) + ".jpg"
    print(image_name)
    cv2.imshow('CROPPED '+str(i), cropped_contour)
    cv2.waitKey(0)
    cv2.imwrite(image_name, cropped_contour)
    
cv2.destroyAllWindows()




output_shape_number_1.jpg
output_shape_number_2.jpg
output_shape_number_3.jpg
output_shape_number_4.jpg


shelf.jpg

In [12]:
import cv2
import numpy as np

# Functions we'll use for sorting by position

def x_cord_contour(contours):
    #Returns the X cordinate for the contour centroid
    if cv2.contourArea(contours) > 10:
        M = cv2.moments(contours)
        return (int(M['m01']/M['m00']))
    else:
        pass

    
def label_contour_center(image, c):
    # Places a red circle on the centers of contours
    M = cv2.moments(c)
    cx = int(M['m10'] / M['m00'])
    cy = int(M['m01'] / M['m00'])
 
    # Draw the countour number on the image
    cv2.circle(image,(cx,cy), 10, (0,0,255), -1)
    return image


# Load our image
image = cv2.imread('shelf.jpg')
orginal_image = image.copy()

gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

edged = cv2.Canny(gray, 50, 200)

contours, hierarchy = cv2.findContours(edged.copy(),
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_NONE)
# Computer Center of Mass or centroids and draw them on our image
for (i, c) in enumerate(contours):
    orig = label_contour_center(image, c)
 
    cv2.imshow("4 - Contour Centers ", image)
    cv2.waitKey(0)

# Sort by left to right using our x_cord_contour function
contours_left_to_right = sorted(contours, 
                                key = x_cord_contour, 
                                reverse = False)


# Labeling Contours left to right
for (i,c)  in enumerate(contours_left_to_right):
    cv2.drawContours(orginal_image, [c], -1, (0,0,255), 3)  
    M = cv2.moments(c)
    cx = int(M['m10'] / M['m00'])
    cy = int(M['m01'] / M['m00'])
    cv2.putText(orginal_image, str(i+1), (cx, cy), 
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('6 - Left to Right Contour', orginal_image)
    cv2.waitKey(0)
    (x, y, w, h) = cv2.boundingRect(c)  
    
    # Let's now crop each contour and save these images
    cropped_contour = orginal_image[y:y + h, x:x + w]
    image_name = "output_shape_number_" + str(i+1) + ".jpg"
    cv2.imshow('CROPPED '+str(i), cropped_contour)
    cv2.waitKey(0)
    
    
cv2.destroyAllWindows()


