   ## Line Detection - Using Hough Lines
   
**cv2.HoughLines**(binarized/thresholded image, 𝜌 accuracy, 𝜃 accuracy, threshold)
- Threshold here is the minimum vote for it to be considered a line


In [2]:
import cv2
import numpy as np

image = cv2.imread('soduku.jpg')

# Grayscale and Canny Edges extracted
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 100, 170, apertureSize = 3)

# Run HoughLines using a rho accuracy of 1 pixel
# theta accuracy of np.pi / 180 which is 1 degree
# Our line threshold is set to 240 (number of points on line)
lines = cv2.HoughLines(edges, 1, np.pi / 180, 230)
print(lines)
# We iterate through each line and convert it to the format
# required by cv.lines (i.e. requiring end points)
for line in lines:
    rho = line[0][0]
    theta = line[0][1]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(image, (x1, y1), (x2, y2), (255, 0, 0), 2)
cv2.imshow('canny', edges)

cv2.imshow('Hough Lines', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[   4.           2.8797932]]

 [[   2.           2.8797932]]

 [[ 637.           1.2566371]]

 [[ -77.           2.8274333]]

 [[ 507.           1.2740903]]

 [[-476.           2.6179938]]

 [[ 505.           1.2740903]]

 [[-130.           2.7925267]]

 [[ 379.           1.2915436]]

 [[ 323.           1.2915436]]

 [[ -21.           2.86234  ]]

 [[ 634.           1.2566371]]

 [[ -24.           2.86234  ]]

 [[ 574.           1.2566371]]

 [[-387.           2.6703537]]

 [[  21.           2.8797932]]

 [[-284.           2.7052603]]

 [[-429.           2.6354473]]

 [[ -75.           2.8274333]]

 [[-128.           2.7925267]]

 [[ 381.           1.2915436]]

 [[-485.           2.6354473]]

 [[-282.           2.7052603]]

 [[ 121.           1.3089969]]

 [[ 384.           1.2740903]]

 [[ 437.           1.2915436]]

 [[ 442.           1.2740903]]

 [[ 218.           1.2915436]]

 [[ 569.           1.2740903]]

 [[ 214.           1.3089969]]

 [[ 268.           1.3089969]]

 [[-505.

### Probabilistic Hough Lines

**cv2.HoughLinesP(binarized image, 𝜌 accuracy, 𝜃 accuracy, threshold, minimum line length, max line gap)




In [9]:
import cv2
import numpy as np

# Grayscale and Canny Edges extracted
image = cv2.imread('soduku.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 100, 170, apertureSize = 3)

# Again we use the same rho and theta accuracies
# However, we specific a minimum vote (pts along line) of 100
# and Min line length of 5 pixels and max gap between lines of 10 pixels
lines = cv2.HoughLinesP(edges, 1, np.pi / 180, 50, 50, 10)
print( lines.shape)
# print( lines)

for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(image, (x1, y1), (x2, y2),(0, 255, 0), 3)

cv2.imshow('Probabilistic Hough Lines', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(979, 1, 4)
