# Circle Detection - Hough Cirlces

**cv2.HoughCircles**(image, method, dp, MinDist, param1, param2, minRadius, MaxRadius)


- Method - currently only cv2.HOUGH_GRADIENT available
- dp - Inverse ratio of accumulator resolution
- MinDist - the minimum distance between the center of detected circles
- param1 - Gradient value used in the edge detection
- param2 - Accumulator threshold for the HOUGH_GRADIENT method (lower allows more circles to be detected (false positives))
- minRadius - limits the smallest circle to this size (via radius)
- MaxRadius - similarly sets the limit for the largest circles



In [1]:
import cv2
import numpy as np
# import cv2.cv as cv

image = cv2.imread('opencv-logo-1.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

blur = cv2.medianBlur(gray, 5)

circles = cv2.HoughCircles(blur,
                           cv2.cv2.HOUGH_GRADIENT,
                           1,50,
                        param1=50,
                           param2=30,
                           minRadius=50,
                           maxRadius=200)

print(circles)
circles = np.uint16(np.around(circles))
print(circles)
for i in circles[0,:]:
    # draw the outer circle
    cv2.circle(image,(i[0], i[1]), i[2], (255, 0, 0), 2)
    
    # draw the center of the circle
    cv2.circle(image, (i[0], i[1]), 5, (0, 255, 0), -1)

cv2.imshow('detected circles', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[364.5 287.5  96.1]
  [253.5  96.5  96.8]
  [146.5 287.5  96.2]]]
[[[364 288  96]
  [254  96  97]
  [146 288  96]]]


In [2]:
circles[0,:]

array([[364, 288,  96],
       [254,  96,  97],
       [146, 288,  96]], dtype=uint16)

In [3]:
cv2.__version__

'4.5.2'