## Finding Corners

In [7]:
import cv2
import numpy as np

# Load image then grayscale
image = cv2.imread('chess.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# The cornerHarris function requires the array datatype to be float32
gray = np.float32(gray)

harris_corners = cv2.cornerHarris(gray, 3, 3, 0.05)

#We use dilation of the corner points to enlarge them\
# kernel = np.ones((7,7),np.uint8)
# harris_corners = cv2.dilate(harris_corners, kernel, iterations = 2)
print(harris_corners.shape)

print(image.shape)
# Threshold for an optimal value, it may vary depending on the image.
image[harris_corners > 0.025 * harris_corners.max() ] = [0,
                                                         255,
                                                         0]

cv2.imshow('Harris Corners', image)
cv2.imwrite('Harris Corners.jpg',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(608, 609)
(608, 609, 3)


In [3]:
harris_corners[0,0]

-8163.3623

In [4]:
harris_corners.min()

-93595736.0

In [5]:
harris_corners.max()

248225540.0

In [6]:
harris_corners > 0.025 * harris_corners.max() 

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

https://en.wikipedia.org/wiki/Harris_corner_detector


**cv2.cornerHarris**(input image, block size, ksize, k)
- Input image - should be grayscale and float32 type.
- blockSize - the size of neighborhood considered for corner detection
- ksize - aperture parameter of Sobel derivative used.
- k - harris detector free parameter in the equation
- **Output** – array of corner locations (x,y)




## Improved Corner Detection using - Good Features to Track

In [8]:
import cv2
import numpy as np

img = cv2.imread('chess.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# We specific the top 50 corners
corners = cv2.goodFeaturesToTrack(gray, 50, 0.02, 40)
print(len(corners))

for corner in corners:
    print(corner)
    x, y = corner[0]
    x = int(x)
    y = int(y)
    cv2.rectangle(img,(x-10,y-10),(x+10,y+10),(0,255,0), -1)
    
cv2.imshow("Corners Found", img)
cv2.waitKey()
cv2.destroyAllWindows()

49
[[76. 75.]]
[[380.  75.]]
[[ 76. 151.]]
[[152.  76.]]
[[304.  76.]]
[[532.  75.]]
[[381. 533.]]
[[456.  76.]]
[[228.  75.]]
[[381. 303.]]
[[380. 152.]]
[[381. 227.]]
[[381. 457.]]
[[151. 151.]]
[[ 76. 533.]]
[[457. 533.]]
[[532. 151.]]
[[151. 533.]]
[[381. 381.]]
[[457. 227.]]
[[457. 151.]]
[[227. 151.]]
[[ 76. 227.]]
[[227. 533.]]
[[ 76. 304.]]
[[ 76. 456.]]
[[227. 227.]]
[[533. 533.]]
[[303. 303.]]
[[151. 227.]]
[[305. 457.]]
[[532. 227.]]
[[305. 379.]]
[[304. 532.]]
[[227. 381.]]
[[304. 151.]]
[[227. 457.]]
[[ 76. 380.]]
[[303. 227.]]
[[151. 457.]]
[[227. 303.]]
[[151. 303.]]
[[457. 303.]]
[[456. 380.]]
[[533. 457.]]
[[457. 457.]]
[[532. 304.]]
[[151. 381.]]
[[533. 380.]]


**cv2.goodFeaturesToTrack**(input image, maxCorners, qualityLevel, minDistance)

- Input Image - 8-bit or floating-point 32-bit, single-channel image.
- maxCorners – Maximum number of corners to return. If there are more corners than are found, the strongest of them is returned.
- qualityLevel – Parameter characterizing the minimal accepted quality of image corners. The parameter value is multiplied by the best corner quality measure (smallest eigenvalue). The corners with the quality measure less than the product are rejected. For example, if the best corner has the quality measure = 1500, and the  qualityLevel=0.01 , then all the corners with the quality - - measure less than 15 are rejected.
- minDistance – Minimum possible Euclidean distance between the returned corners.
